name: Build and Package R Package

# 触发时机：与 R-hub 工作流错开或并行（按需调整）
on:
  push:
    tags:
      - 'v*'
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Build package
        run: |
          pkg_file <- devtools::build()
          echo "PKG_FILE=$pkg_file" >> $GITHUB_ENV
        shell: bash {0}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: r-package
          path: ${{ env.PKG_FILE }}

      - name: Attach to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ steps.get_tag_message.outputs.tag_message }}
          files: ${{ env.PKG_FILE }}